### ISSUE TITLE
Please relicense under MIT or MPL2

### ISSUE THREAD

**Issue by TheColonel2688** [stefanbesler/Twinson#2]
Please relicense under MIT or MPL2.

GPL is a cancer and is very restrictive.

**Comment by stefanbesler** [comment]
Sorry, ain’t gonna happen, I have reasons why I license with GPLv3. And it is not cancerous, it is just infectious, by design.

I don’t want companies to use my source code commercially for free without using a copyleft license themselves. Dual licensing I am ok with, if you are interested in this you can contact me privately
